# backend/app/api/personas.py
"""Configuring the simulated humans that share an environment with the agent.

The cast lives in the `personas:` block of an environment's
`custom/config.yaml` — the same file the YAML editor edits — rather than in a
file of its own. One source of truth means the two editors can never disagree,
and an author who prefers YAML keeps working exactly as before.

Reads and writes go through `forge.personas.config`, so the API rejects a
misspelled trait or an out-of-range dial with the same message the runtime
would, instead of accepting it and producing an environment that behaves
nothing like the one that was configured.
"""
from __future__ import annotations

from pathlib import Path

import yaml
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from forge.contracts.persona import PersonaPopulation, PersonaSpec
from forge.personas.config import (
    PersonaConfigError,
    dump_population,
    dump_spec,
    load_population,
)
from forge.personas.population import PersonaPopulationError, resolve_roster
from forge.runtime.tools import RESERVED_PATHS, RESERVED_PREFIX
from forge.settings import generated_envs_root

router = APIRouter(prefix="/api/envs")


def _validate_env_name(env_name: str) -> None:
    if ".." in env_name or "/" in env_name or "\\" in env_name:
        raise HTTPException(status_code=400, detail="Invalid environment name")


def _config_path(env_name: str, create: bool = False) -> Path:
    """The environment's config file, whether or not it exists yet.

    Container environments generated by the custom builder have no `custom/`
    directory until something writes one — the compiler creates it, the envgen
    pipeline does not. 404ing on its absence would make the personas page dead
    for exactly the environments the builder produces, so the directory is
    created on write and a missing file simply reads as an empty config.
    """
    _validate_env_name(env_name)
    env_dir = generated_envs_root() / env_name
    if not env_dir.is_dir():
        raise HTTPException(
            status_code=404, detail=f"Environment '{env_name}' not found"
        )
    custom_dir = env_dir / "custom"
    if create:
        custom_dir.mkdir(parents=True, exist_ok=True)
    return custom_dir / "config.yaml"


def _read_config(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return yaml.safe_load(path.read_text()) or {}
    except yaml.YAMLError as exc:
        raise HTTPException(
            status_code=422, detail=f"config.yaml is not valid YAML: {exc}"
        )


class PersonaPayload(BaseModel):
    """The cast, plus what the editor needs to render controls for it."""

    personas: dict
    environment_actions: list[str] = Field(default_factory=list)


class PersonaUpdate(BaseModel):
    personas: dict


class EnabledUpdate(BaseModel):
    """The one-field edit the agent-run launcher makes."""

    enabled: bool


class PreviewRequest(BaseModel):
    """Which cast a given seed would actually produce."""

    personas: dict
    seed: int = 0


class PreviewResponse(BaseModel):
    roster: list[dict]
    warnings: list[str] = Field(default_factory=list)


def _environment_actions(env_name: str) -> list[str]:
    """The action types this environment implements.

    Read from the generated `transitions/` directory, which holds one module
    per action named after it, rather than by importing the environment —
    importing would mean executing generated code inside the API process. An
    environment whose surface cannot be read yields an empty list, and the
    editor degrades to free text rather than failing.
    """
    env_dir = generated_envs_root() / env_name
    transitions = env_dir / "transitions"
    if transitions.is_dir():
        return sorted(
            path.stem
            for path in transitions.glob("*.py")
            if not path.stem.startswith("_")
        )
    return _container_endpoints(env_dir / "app")


def _container_endpoints(app_dir: Path) -> list[str]:
    """POST routes of a generated FastAPI app, as the runtime sees them.

    A container environment's actions are endpoint paths, not names: the
    episode runner discovers them from /openapi.json and posts to them
    directly. That schema only exists while the container is running, so the
    routes are read from source instead — the same POST-only, /forge/- and
    /ui-excluded surface `OpenAPIToolProvider` builds, without needing the
    environment to be up.
    """
    import ast

    if not app_dir.is_dir():
        return []
    found: set[str] = set()
    for path in sorted(app_dir.rglob("*.py")):
        try:
            tree = ast.parse(path.read_text(encoding="utf-8", errors="replace"))
        except (SyntaxError, OSError):
            continue
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            func = node.func
            # `@app.post("/x")` and `@router.post("/x")` — the decorator is a
            # call on an attribute named for the HTTP method.
            if not isinstance(func, ast.Attribute) or func.attr != "post":
                continue
            if not node.args:
                continue
            route = node.args[0]
            if not isinstance(route, ast.Constant) or not isinstance(route.value, str):
                continue
            if route.value.startswith(RESERVED_PREFIX) or route.value in RESERVED_PATHS:
                continue
            found.add(route.value)
    return sorted(found)


@router.get("/{env_name}/personas", response_model=PersonaPayload)
def get_personas(env_name: str) -> PersonaPayload:
    path = _config_path(env_name)
    raw = _read_config(path)
    try:
        population = load_population(raw.get("personas"))
    except PersonaConfigError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    return PersonaPayload(
        personas=dump_population(population),
        environment_actions=_environment_actions(env_name),
    )


@router.put("/{env_name}/personas", response_model=PersonaPayload)
def update_personas(env_name: str, payload: PersonaUpdate) -> PersonaPayload:
    path = _config_path(env_name, create=True)
    try:
        population = load_population(payload.personas)
    except PersonaConfigError as exc:
        raise HTTPException(status_code=422, detail=str(exc))

    _reject_unknown_actions(env_name, population)

    raw = _read_config(path)
    # Rewritten in place: everything else in config.yaml — reward weights,
    # observation filtering — must survive an edit made from the persona page.
    raw["personas"] = dump_population(population)
    path.write_text(yaml.safe_dump(raw, sort_keys=False))
    return PersonaPayload(
        personas=raw["personas"],
        environment_actions=_environment_actions(env_name),
    )


@router.put("/{env_name}/personas/enabled", response_model=PersonaPayload)
def set_personas_enabled(env_name: str, payload: EnabledUpdate) -> PersonaPayload:
    """Switch the cast on or off without touching who is in it.

    Separate from the full PUT so the launcher can flip one flag without
    round-tripping a roster it never rendered — a launcher that had to send the
    whole population back would overwrite any edit made on the personas page
    since it loaded.
    """
    path = _config_path(env_name, create=True)
    raw = _read_config(path)
    try:
        population = load_population(raw.get("personas"))
    except PersonaConfigError as exc:
        raise HTTPException(status_code=422, detail=str(exc))

    if payload.enabled and not population.roster and not population.archetypes:
        raise HTTPException(
            status_code=422,
            detail=(
                f"'{env_name}' has no people configured yet. Add someone on the "
                "Simulated People page before turning them on."
            ),
        )

    raw["personas"] = dump_population(
        population.model_copy(update={"enabled": payload.enabled})
    )
    path.write_text(yaml.safe_dump(raw, sort_keys=False))
    return PersonaPayload(
        personas=raw["personas"],
        environment_actions=_environment_actions(env_name),
    )


@router.post("/{env_name}/personas/preview", response_model=PreviewResponse)
def preview_personas(env_name: str, payload: PreviewRequest) -> PreviewResponse:
    """The cast a seed produces, without running an episode.

    `count` above the roster size clones archetypes, so what an author
    configures and what an episode actually contains are not the same list.
    Showing the resolved cast is the difference between configuring four
    personas and discovering four personas.
    """
    _validate_env_name(env_name)
    try:
        population = load_population(payload.personas)
    except PersonaConfigError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    try:
        roster = resolve_roster(population, payload.seed)
    except PersonaPopulationError as exc:
        raise HTTPException(status_code=422, detail=str(exc))
    return PreviewResponse(
        roster=[dump_spec(spec) for spec in roster],
        warnings=_warnings(env_name, roster),
    )


def _warnings(env_name: str, roster: list[PersonaSpec]) -> list[str]:
    """Configuration that is valid but will not do what its author expects.

    Distinct from the errors that block a save: these are castings that load,
    run, and quietly do nothing — the failure mode an author is least likely to
    diagnose on their own.
    """
    warnings: list[str] = []
    known = set(_environment_actions(env_name))
    for spec in roster:
        name = spec.profile.name
        if not spec.behavior.allowed_actions:
            warnings.append(f"{name} has no allowed actions and will never act.")
            continue
        if known:
            unknown = sorted(set(spec.behavior.allowed_actions) - known)
            if unknown:
                warnings.append(
                    f"{name} is allowed {', '.join(unknown)}, which this "
                    "environment does not implement."
                )
        if spec.behavior.activity == 0 and not spec.behavior.wake_on:
            # Reachable only by an agent action, and `wake_on: []` means any
            # action wakes them — so this one is fine. Nothing to warn about.
            continue
        if spec.behavior.activity == 0 and spec.behavior.max_actions_per_episode == 0:
            warnings.append(
                f"{name} has a zero action budget and will never act."
            )
    return warnings


def _reject_unknown_actions(env_name: str, population: PersonaPopulation) -> None:
    """Refuse to save a cast bound to actions the environment does not have.

    The same check `EnvBuilder.build()` makes. Catching it here means an author
    sees the mistake while editing rather than when the next rollout starts.
    """
    known = set(_environment_actions(env_name))
    if not known:
        # The surface could not be read. Saving is still allowed — the build
        # will catch it — rather than blocking on our inability to introspect.
        return
    for spec in [*population.roster, *population.archetypes]:
        unknown = sorted(set(spec.behavior.allowed_actions) - known)
        if unknown:
            raise HTTPException(
                status_code=422,
                detail=(
                    f"persona '{spec.profile.id}' is allowed action(s) "
                    f"{', '.join(unknown)}, which '{env_name}' does not "
                    f"implement. Available: {', '.join(sorted(known))}"
                ),
            )
